### ISSUE TITLE
Problem with package usage

### ISSUE THREAD

**Issue by tub-rmueller** [simon-pfahler/colorblind#4]
Hello!

I tried to use the T-D-N color scheme of the package for a bar chart with TikZ. Unfortunately, I couldn't figure out how to get it running. I integrated it in the preambel as follows:

\documentclass[10pt, border={0mm 0mm 0mm 5mm}]{standalone}
\usepackage[T1]{fontenc}
\usepackage{newtxtext,newtxmath}
\usepackage[utf8]{inputenc}
\usepackage{siunitx}
\usepackage{tikz}
\usepackage{colorblind}[Tol,pgf]
\usepackage{pgfplots}
\usepackage{pgfplotstable}
\pgfplotsset{
	every axis plot/.append style={thin},
	ytick style={draw=none},
	yticklabel style={align=center, font=\small}
}
\usetikzlibrary{patterns}

In the tikzpicture, each bar plot was then added using 

\addplot+[fill=T-D-N7, draw=black]

However, I get the following error message: ! Package xcolor Error: Undefined color T-D-N7'.

Could anybody help?

**Comment by simon-pfahler** [comment]
The package options [Tol, pgf] have to be provided in front of the package, so you should write `\usepackage[Tol, pgf]{colorblind}`, not the other way around.
